---
- name: Set allow-interfaces in /etc/avahi/avahi-daemon.conf
  ansible.builtin.shell:
    cmd: sed -i 's/#allow-interfaces=eth0/allow-interfaces={{  allow_interfaces  }}/g' /etc/avahi/avahi-daemon.conf

- name: Enable reflector in /etc/avahi/avahi-daemon.conf
  ansible.builtin.shell:
    cmd: sed -i 's/#enable-reflector=no/enable-reflector=yes/g' /etc/avahi/avahi-daemon.conf
