---
- name: Add buster repository to sources list
  ansible.builtin.shell:
    cmd: |
      echo "deb http://ftp.us.debian.org/debian buster main contrib" >> /etc/apt/sources.list
      echo "deb-src http://ftp.us.debian.org/debian buster main contrib" >> /etc/apt/sources.list
      echo "deb http://ftp.us.debian.org/debian buster-updates main contrib" >> /etc/apt/sources.list
      echo "deb-src http://ftp.us.debian.org/debian buster-updates main contrib" >> /etc/apt/sources.list      

- name: Install python3-apt to use "ansible.builtin.apt"
  ansible.builtin.shell:
    cmd: apt update && apt install --no-install-recommends python3-apt -y -q

- name: Install mDNS packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ item }}"
  loop:
    - "{{ mdns_packages }}"

- name: Remove buster from /etc/apt/sources.list
  ansible.builtin.shell:
    cmd: sed -i '/main contrib/d' /etc/apt/sources.list
    