---
- name: Check if avahi-daemon is installed (will say "OK" if not installed)
  command: dpkg-query -W avahi-daemon
  register: avahi_daemon_check_deb
  failed_when: avahi_daemon_check_deb.rc > 1
  changed_when: avahi_daemon_check_deb == 1

- name: Add buster repository to sources list
  ansible.builtin.shell:
    cmd: |
      echo "deb http://ftp.us.debian.org/debian buster main contrib" >> /etc/apt/sources.list
      echo "deb-src http://ftp.us.debian.org/debian buster main contrib" >> /etc/apt/sources.list
      echo "deb http://ftp.us.debian.org/debian buster-updates main contrib" >> /etc/apt/sources.list
      echo "deb-src http://ftp.us.debian.org/debian buster-updates main contrib" >> /etc/apt/sources.list      
  when: avahi_daemon_check_deb.rc == 1  

- name: Install python3-apt to use "ansible.builtin.apt"
  ansible.builtin.shell:
    cmd: apt update && apt install --no-install-recommends python3-apt -y -q
  when: avahi_daemon_check_deb.rc == 1  

- name: Install the build dependencies for package "avahi-daemon"
  ansible.builtin.apt:
    pkg: avahi-daemon
    state: build-dep
  when: avahi_daemon_check_deb.rc == 1  

- name: Install avahi-daemon
  ansible.builtin.apt:
    deb: http://ftp.us.debian.org/debian/pool/main/a/avahi/avahi-daemon_{{ avahi_daemon_version }}_{{ architecture }}.deb
  when: avahi_daemon_check_deb.rc == 1  

- name: Remove buster from /etc/apt/sources.list
  ansible.builtin.shell:
    cmd: sed -i '/main contrib/d' /etc/apt/sources.list
  when: avahi_daemon_check_deb.rc == 1  
