---
- name: Install avahi-daemon, libnss-mdns, avahi-utils
  import_tasks: install_all_packages.yml

- name: Configure avahi-daemon
  import_tasks: configure_avahi_daemon.yml

- name: Restart avahi-daemon
  import_tasks: restart_avahi_daemon.yml
